// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTgBDqRwI2NrWxz39RG3rDBJfH4SgiwyA',
    appId: '1:887836983106:web:00f0e83a92ec130f3d12db',
    messagingSenderId: '887836983106',
    projectId: 'game-startup-ai-agent',
    authDomain: 'game-startup-ai-agent.firebaseapp.com',
    storageBucket: 'game-startup-ai-agent.firebasestorage.app',
    measurementId: 'G-5Y2J4QFGWS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9BMnCX1WeOUdmEQxCHFki-EVOG42m1LU',
    appId: '1:887836983106:ios:e47c5c348b291a213d12db',
    messagingSenderId: '887836983106',
    projectId: 'game-startup-ai-agent',
    storageBucket: 'game-startup-ai-agent.firebasestorage.app',
    iosBundleId: 'com.enoch.gamingStartupAiAgent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTgBDqRwI2NrWxz39RG3rDBJfH4SgiwyA',
    appId: '1:887836983106:web:2bc4fd676f57bce73d12db',
    messagingSenderId: '887836983106',
    projectId: 'game-startup-ai-agent',
    authDomain: 'game-startup-ai-agent.firebaseapp.com',
    storageBucket: 'game-startup-ai-agent.firebasestorage.app',
    measurementId: 'G-993XC78N0H',
  );
}
